### ISSUE TITLE
bug: DivInput adds an extra newline at the end of every line

### ISSUE THREAD

**Issue by tpguy825** [face-hh/lyntr#13]
e.g.
```
Some text

Some more text
```
once posted becomes
```
Some text


Some more text
```
The problem seems to be with [DivInput.svelte](https://github.com/face-hh/lyntr/blob/master/src/routes/DivInput.svelte)

![image](https://github.com/user-attachments/assets/72a4ab1f-a763-4cd6-a058-05a8f5beee4f)
becomes
![image](https://github.com/user-attachments/assets/03210745-a7f9-404c-8ffd-baf4c4c6c808)

**Comment by face-hh** [comment]
A solution found on stackoverflow:
```js
div.addEventListener("keydown", e => {
  if (e.which == 13) {
    e.stopPropagation();
    e.preventDefault();
    document.execCommand('insertHTML', false, '<br>');
  }
});
```

**Comment by face-hh** [comment]
I'll check this out in a bit

**Comment by face-hh** [comment]
Fixed in the latest commit
