### ISSUE TITLE
Long comments doesn't get sent

### ISSUE THREAD

**Issue by mxjeonsg** [face-hh/lyntr#14]
Well, it's me again, sadly, and this is my first time using Github issue filing, sadly.

Going through Lyntr, i found someone commented my repost of a mouse image:
![Screenshot_2024-07-29_23-07-32](https://github.com/user-attachments/assets/9e76deae-c8ca-4f7b-b403-575aaff0a914)
and i tried to answer with a ChatGPT generated "polite" answer, being my prompt "the most verbose way possible".
This is the answer i tried to comment:
![Screenshot_2024-07-29_23-09-25](https://github.com/user-attachments/assets/93de0404-385e-40f0-a92e-51fd5c1eabb3)
Which according to Linux command ["wc"](https://linux.die.net/man/1/wc) `echo -ne '<comment>' | wc -c` it's 560 characters long.

Now, trying to comment it pops a 400 error "Bad request" according to Chromium's developer tools.
Trying to research a bit by myself (acknowledging my lack of knowing if it goes against Lyntr's Terms of Service, I admit i proceeded anyway.), i went to the last element shown in Network tab, thinking that should be the network request matching my comment attempt.

The payload field according to that last element shows a JSON (screenshot appended) with (presumably) my user identifier, and the content (the full comment i tried to issue). The preview field shows (screenshot appended) "Invalid content" which i guess it's the server's response to my request and the Response tab displaying the same content as preview tab did.

Payload tab mentioned JSON:
![Screenshot_2024-07-29_23-18-55](https://github.com/user-attachments/assets/5140bfd2-82ef-4f34-a84f-db7a45f86450)

Preview tab mentioned "supposed" answer:
![Screenshot_2024-07-29_23-19-37](https://github.com/user-attachments/assets/645179cd-063b-47a5-9abb-6439aeeb26e5)

Now, there are two hypothesis i encountered throughout my Devtools watch out; the first one being: "maybe this has some kind of character limit" which can be understandable i guess for security reasons, i guess; and the second one being "maybe the server have just fallen down", being discarded with a refresh in my desktop and trying Lyntr on my phone, working successfully (not the extensive comment).

I tried looking through the source code but i got immediately overwhelmed by my lack of knowledge on Typescript and any framework library used in the project (Svelte apparently) and giving up on the research for my aforementioned "character limit on comments".

I fill up this issue instead of asking on Discord to maybe let people know (with no bad intention) that "issue" exist.

I'll follow up looking forward to any response on this issue filling (accepting whichever response i get or whichever consequence i get to receive by using Devtools).

**Comment by face-hh** [comment]
Hey,

The character limit is 280. The comment tab is still lacking a character counter like the Post button has.

**Comment by mxjeonsg** [comment]
Oh, thank you, I really appreciate it. I didn't noticed about a character limit on comments, and correctly a character counter like Post form has will be extremely helpful. In any way, thank you for the attention and I really appreciate the response. I'm marking the issue as resolved. Thank you once again.
