### ISSUE TITLE
[Feature Request] add google or github login support

### ISSUE THREAD

**Issue by dot166** [face-hh/lyntr#24]
Some people do not have discord

**Comment by Celestemysterios** [comment]
yes please i dont have discord and will never have it again

**Comment by 06NinjaKid06** [comment]
I mean discord is a pretty good way of making sure you are 13+

**Comment by dot166** [comment]
> I mean discord is a pretty good way of making sure you are 13+

Google is also a good way

**Comment by Celestemysterios** [comment]
> I mean discord is a pretty good way of making sure you are 13+
yeah but i was addicted to it and i really dont want to get addicted again

**Comment by Celestemysterios** [comment]
> > I mean discord is a pretty good way of making sure you are 13+
> 
> Google is also a good way

have you heard of the term "lying about your age"

**Comment by dot166** [comment]
> > > I mean discord is a pretty good way of making sure you are 13+
> > 
> > 
> > Google is also a good way
> 
> have you heard of the term "lying about your age"

You could probably do that on discord as well

**Comment by Sovenok-Hacker** [comment]
> I mean discord is a pretty good way of making sure you are 13+

Ok, I am 13

**Comment by DictatePM** [comment]
The servers are overloaded and giving 502 errors everywhere. I think they should add it a few days later, when the hype has died down a little. Imagine how the servers would be right now if that was a thing. 107% CPU usage

**Comment by face-hh** [comment]
Sorry but it's either Discord either we spend a lot of time fighting alts

**Comment by Celestemysterios** [comment]
> Sorry but it's either Discord either we spend a lot of time fighting alts

cant people just make alts on discord?

**Comment by 901238746** [comment]
That requires phone verification.

**Comment by Celestemysterios** [comment]
> That requires phone verification.

wdym?
