### ISSUE TITLE
Website is slow

### ISSUE THREAD

**Issue by Mike-FreeAI** [face-hh/lyntr#27]

**Comment by ttvhipo** [comment]
GOD same here

**Comment by Sovenok-Hacker** [comment]
Ya

**Comment by Mike-FreeAI** [comment]
Database updated

**Comment by Sovenok-Hacker** [comment]
Will it help?

**Comment by Mike-FreeAI** [comment]
Idk

**Comment by Sovenok-Hacker** [comment]
Me too

**Comment by ttvhipo** [comment]
i dont think it helped...

**Comment by Sovenok-Hacker** [comment]
ya

**Comment by Sovenok-Hacker** [comment]
the server is overloaded

**Comment by Mike-FreeAI** [comment]
the issue where lyntr takes like 2 minutes to load is known

ill fix more stuff tomorrow <:SickBro:1058027132309209199> please report any bad posts, and dont make bad posts

**Comment by Sovenok-Hacker** [comment]
It crashed ;)

**Comment by face-hh** [comment]
This is known, and it's a database issue.
