### ISSUE TITLE
Wrong type of input for in Profile Settings

### ISSUE THREAD

**Issue by RicardoPinto26** [face-hh/lyntr#32]
The inputs for changing your Username and About Me have the type email, which the browser detects and prompts the user to input an email.
![image](https://github.com/user-attachments/assets/ce38e0e6-d76e-4fa2-b916-c990d2dd1507)

Issue is in the following file+lines:

src/routes/ProfileSettings.svelte

Line 79:
```svelte
<Input type="email" id="email" placeholder="Username" bind:value={username} />
Changes to:
<Input type="text" id="email" placeholder="Username" bind:value={username} />
```
Line 84:
```svelte
<Input type="email" id="email" placeholder="About me..." bind:value={bio} />
Changes to:
<Input type="text" id="email" placeholder="About me..." bind:value={bio} />
```

**Comment by Waradu** [comment]
why not make a pr?

**Comment by GamebP** [comment]
> why not make a pr?

Bro is lazy

**Comment by RicardoPinto26** [comment]
> why not make a pr?



> > why not make a pr?
> 
> Bro is lazy

Rule 1 of contributing:
"Don't open pull requests that simply fix grammatical issues or such. Open an issue instead."

The fix is simply changing 2 words and it's not critical, so I'm guessing the hassle of dealing with a pull request is not worth.

**Comment by Waradu** [comment]
> Rule 1 of contributing: "Don't open pull requests that simply fix grammatical issues or such. Open an issue instead."
> 
> The fix is simply changing 2 words and it's not critical, so I'm guessing the hassle of dealing with a pull request is not worth.

Fixing small things like typos is helpful. Most projects prefer direct PRs for these as they still improve the overall product and reduce extra steps for maintainers.

But it doesn't matter because GStudiosX already fixed it.
