### ISSUE TITLE
Ban api endpoint will revoke the token for the client

### ISSUE THREAD

**Issue by Zippybonzo** [face-hh/lyntr#33]
`const token = cookies.get('authToken');
		if (token) {
			await deleteJWT(token);
		}`

this line in src/api/ban/+server.ts would surely revoke the token for the client making such api request, not the user being banned?

**Comment by face-hh** [comment]
Probably, but it doesn't really matter since the server will not accept the token anyway. It should be removed though

**Comment by face-hh** [comment]
Fixed in next rebuild.
