### ISSUE TITLE
Access token in the website title

### ISSUE THREAD

**Issue by Redo11** [face-hh/lyntr#37]
![image](https://github.com/user-attachments/assets/9baba6b0-ecca-4a2e-abb3-1ab6a0e9368b)
That's bad

**Comment by GStudiosX2** [comment]
> ![image](https://private-user-images.githubusercontent.com/49594490/355220772-9baba6b0-ecca-4a2e-abb3-1ab6a0e9368b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTQ5MzMsIm5iZiI6MTcyMjg5NDYzMywicGF0aCI6Ii80OTU5NDQ5MC8zNTUyMjA3NzItOWJhYmE2YjAtZWNjYS00YTJlLWFiYjMtMWFiNmEwZTkzNjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIxNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZWIxYTE0YWI3Y2JlMmI5ODcxYjRlZTFmODc2NjhlMWUwODIzODYyMDE2ODRmYTJiMWUyODgyNzZkNWY1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fFjoY_8XxPymzVauLZ4lPpnOoeAR_iuCGC0EimAVZQ) That's bad

The access token only has limited permissions anyway (read profile & email)

**Comment by face-hh** [comment]
Fixed in next rebuild.
