### ISSUE TITLE
I killed the website

### ISSUE THREAD

**Issue by BoryaGames** [face-hh/lyntr#38]
I tried to register and website died because of it, now it doesn't work for anyone - 522: Connection timed out.

**Comment by MoonCakeToo** [comment]
yea its down 4 me 2

**Comment by 901238746** [comment]
What have you done?

**Comment by MoonCakeToo** [comment]
it got ddosed. consider closing issue?

**Comment by MoonCakeToo** [comment]
ITS BACK!

**Comment by 901238746** [comment]
Wait, it is?
Yay

**Comment by 901238746** [comment]
Its down

**Comment by 901238746** [comment]
Its gone

**Comment by MoonCakeToo** [comment]
uhh its a 521 this baaaad (i think) (im stupid)

**Comment by 901238746** [comment]
Liynter host is having a error according to cloudflare

**Comment by MoonCakeToo** [comment]
oh noes

**Comment by 901238746** [comment]
:(

**Comment by RoboXL** [comment]
Bro why :(

**Comment by 901238746** [comment]
I hate these ddosers. I just want to be in this nice lil website but they always gotta boot there botnet up.

**Comment by BoryaGames** [comment]
Yeah, it was DDoS actually

**Comment by 901238746** [comment]
exactly

**Comment by 901238746** [comment]
Its up!!!

**Comment by 901238746** [comment]
Loading does take a while tho

**Comment by 901238746** [comment]
and its gone again

**Comment by MoonCakeToo** [comment]
up again
