### ISSUE TITLE
Website Crash After Specific Input Attempts

### ISSUE THREAD

**Issue by JustOptimize** [face-hh/lyntr#40]
I attempted to register an empty handle, a single letter handle, "999" in the typing test, and other similar entries. After submitting my final request, the website became unresponsive.

If my actions inadvertently caused this issue, I sincerely apologize.

**Comment by MoonCakeToo** [comment]
a little bit of tomfoolery

**Comment by MoonCakeToo** [comment]
#38 #39

**Comment by JustOptimize** [comment]
Ok, just joined the discord server, the vps got ddossed, not my fault yey

**Comment by MoonCakeToo** [comment]
oh
