### ISSUE TITLE
Sites manifest failing to load.

### ISSUE THREAD

**Issue by 901238746** [face-hh/lyntr#42]
According to console the sites manifest is having syntax errors and the get request is forbidden. could be why loading takes forever. could be due to a ddosing attack.

**Comment by 901238746** [comment]
line 1 is broken

**Comment by GStudiosX2** [comment]
> According to console the sites manifest is having syntax errors and the get request is forbidden. could be why loading takes forever. could be due to a ddosing attack.

There is no manifest it leads to a 404 error that's why it says it has syntax errors

**Comment by 901238746** [comment]
Its own manifest is broken. looking into source it has a manifest yet its syntax sucks. probally cause it cant fetch the actuall maifest.

**Comment by 901238746** [comment]
It doesnt even matter
