### ISSUE TITLE
Test Values Stored in local storage can be modified.

### ISSUE THREAD

**Issue by ironland-web** [face-hh/lyntr#47]
Several Values such a WPM test can be changed to manipulate IQ.

![Screenshot 2024-08-05 205802](https://github.com/user-attachments/assets/7e7932f6-e58f-4714-b434-ed9fb53ad438)
![Screenshot 2024-08-05 205828](https://github.com/user-attachments/assets/bdbe95cd-71b0-4e37-b578-b37a3f750051)

**Comment by face-hh** [comment]
Intended behavior
