### ISSUE TITLE
Spamming 

### ISSUE THREAD

**Issue by ironland-web** [face-hh/lyntr#48]
I have noticed lots of what i assume to be bots posting the same thing over and over again; There needs to be a time limit between posts and/or not allow multiable identical posts.

**Comment by GStudiosX2** [comment]
> I have noticed lots of what i assume to be bots posting the same thing over and over again; There needs to be a time limit between posts and/or not allow multiable identical posts.

There is a ratelimit but I think it's 5 seconds ideally should maybe disallow the same post by the same user within a certain time period

**Comment by sweglord227** [comment]
that won't help either. i can just add a `.` or something similar to additional posts. a less naive, more thought out approach is needed

**Comment by face-hh** [comment]
A ratelimit has been added.
