### ISSUE TITLE
Login Impossible, returns Timeout

### ISSUE THREAD

**Issue by zvdxc** [face-hh/lyntr#56]
While in https://ytpgdjgfuamiqzogvhqu.supabase.co/auth/v1/authorize?provider=discord

**Comment by zvdxc** [comment]
upstream request timeout

**Comment by tinywifi** [comment]
![image](https://github.com/user-attachments/assets/e36541ba-671c-4354-b301-793fb8bb9020)
they are migrating away from supabase auth so the site is down rn yeah

**Comment by zvdxc** [comment]
OK. Will come back in 42 years :)

**Comment by zvdxc** [comment]
Note: Register and LogIn works, but no commenting / posting

**Comment by zvdxc** [comment]
2. Note: It's only the comments now. 🪄
