### ISSUE TITLE
Allow signing up and logging in without a Discord account

### ISSUE THREAD

**Issue by RealPacket** [face-hh/lyntr#6]
Because why not?
You shouldn't need more than a name and password.

**Comment by face-hh** [comment]
I have skill issues. That, and I don't have time to setup the SMTP whatever the hell server for emails

**Comment by RealPacket** [comment]
> I have skill issues. That, and I don't have time to setup the SMTP whatever the hell server for emails

Then don't require an email, just a username and password!

**Comment by face-hh** [comment]
Prone to spam. I'd rather let Discord handle it

**Comment by RealPacket** [comment]
> Prone to spam. I'd rather let Discord handle it

Yes, however, explain how easy it is to create an account programmatically:
- [ ] Generate a password for use, or a predetermined one (prefer generated passwords, unless you want to be able to sign into them with just 1 password)
- [ ] Send the request
  - [ ] Complete CAPTCHAs if needed (using nopecha, etc.)
  - [ ] If phone number required,
    - [ ] get some random phone number from a temporary phone number site (paid or free, some allow you to have non-VOIP numbers, mostly paid, but some are free)
    - [ ] send in the phone number, if it rejects it, it doesn't accept that phone number, get another one and repeat until it doesn't reject it.
    - [ ] Get the code from the phone number.
  - [ ] If email required,
    - [X] This is even easier.
    - [ ] Get a random email from a provider, temp-mail.org for example
    - [ ] Submit that email to Discord, if it doesn't work, try finding a different email or provider until it works
    - [ ] Get the code from the email.
  - [ ] If CAPTCHA required,
    - [ ] Solve the CAPTCHA using a CAPTCHA solver (e.g. nopecha) 
Plus, even after setting up a SMTP server and other crap, I would like to refer you to how many temporary mail websites there are, and pretty much all of them are free, temp-mail.org is one I used pretty frequently.

**Comment by RealPacket** [comment]
Plus, this is supposed to be a social media website, if Twitter (formerly X) decided that you'll need a Google or Discord account to create a Twitter (formerly X) account, it would be insane. Why would you want to depend on other social media to create a social media account for a different social media website.
Doesn't make sense.
