### ISSUE TITLE
Getting Error 500 when trying to post an image

### ISSUE THREAD

**Issue by GamplaxPramgrammer** [face-hh/lyntr#66]
![image](https://github.com/user-attachments/assets/d9904a2d-e072-48e7-b440-b77a9bb81aaf)
For some reason, when I attach an image to the lynt, the website throws an Error with Error Code: 500 when I try to post the Lynt.

**Comment by justwetmoss** [comment]
+1

**Comment by ironland-web** [comment]
I got this error earlier trying converting it to a png if it is not already a PNG

**Comment by face-hh** [comment]
The servers were down, it should work now.
