### ISSUE TITLE
Discord Login not working

### ISSUE THREAD

**Issue by Body-Alhoha** [face-hh/lyntr#67]
Hello, The discord oauth2 login is currently broken (look attachment)
Expected behavior: Authorize and get logged in Lyntr.
Actual behavior: Invalid oauth redirect url.
How to fix issue: add the following redirect url to Discord App oauth2 redirect urls:
```
https://www.lyntr.com/api/callback
```

Thanks.

![chrome_AK0KDfNUMQ](https://github.com/user-attachments/assets/4c0477c7-a624-490e-84d5-6f88c3d49fb8)

**Comment by Body-Alhoha** [comment]
Edit: only happen on www.lyntr.com and not lyntr.com, seems that the oauth redirect url is from the current subdomain (in this case www) which causes this issue.

**Comment by Rupesh9369** [comment]
Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at web.8d7123b395da2916038a.js:1:10936
    at async Promise.all (/oauth2/index 3)

**Comment by Rupesh9369** [comment]
![image](https://github.com/user-attachments/assets/881f0561-73dd-4925-8be4-2e6c17091ad9)

**Comment by FoxTale-Labs** [comment]
> ![image](https://private-user-images.githubusercontent.com/128808356/355711200-881f0561-73dd-4925-8be4-2e6c17091ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzk2NTQsIm5iZiI6MTcyMzAzOTM1NCwicGF0aCI6Ii8xMjg4MDgzNTYvMzU1NzExMjAwLTg4MWYwNTYxLTczZGQtNDkyNS04YmU0LTJlNmMxNzA5MWFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxNDAyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmNkNjMwZDc4YTM0NDNhMmVlMzA1MTQzYzE5YzIzNTAyYzE0Zjc0MzUyYTAyMzhhY2NiNjFhYjgzMjlkMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kG8HkyBEUV7214y_Pwbu6Tls-A52U8UgXc1AnVAEqG8)

that is unrelated to lyntr as this is a **discord** issue.

**Comment by face-hh** [comment]
Should work now.
