### ISSUE TITLE
API Unaccessable

### ISSUE THREAD

**Issue by ali-kingX** [face-hh/lyntr#74]
Keeps returning 403 error. I've made sure to update my cookie(s).

**Comment by GStudiosX2** [comment]
> Keeps returning 403 error. I've made sure to update my cookie(s).

It's because of the cloud flare challenge

**Comment by ali-kingX** [comment]
@GStudiosX2 So other parts of the API are fine, I can't access https://lyntr.com/api/feed?type=For%20you endpoint atm. I require assistance. This is an issue.

**Comment by GStudiosX2** [comment]
> @GStudiosX2 So other parts of the API are fine, I can't access https://lyntr.com/api/feed?type=For%20you endpoint atm. I require assistance. This is an issue.

You might be able to get everything to work with the Origin header but you can't access any of the API without then`cf_clearance` cookie

**Comment by ali-kingX** [comment]
@GStudiosX2 I have the `cf_clearance` cookie included already...

**Comment by GStudiosX2** [comment]
> @GStudiosX2 I have the `cf_clearance` cookie included already... Always... It just doesn't work...

Yeah I don't know why but sometimes it doesn't work it might be that you need the exact headers or user agent that was used to get the clearance cookie

**Comment by face-hh** [comment]
The API is **not** meant to be used without the frontend. Official API may come out soon
