### ISSUE TITLE
IQ Test Result Calculation Issue

### ISSUE THREAD

**Issue by ArvidSilverlock** [face-hh/lyntr#76]
Correct me if I'm wrong, but the source uses the `Boolean` function to convert the string values to a boolean, in my testing this produced `true` when calling it on `"false"`. Any yes/no questions will result it yes even if you pick no.

**Comment by GStudiosX2** [comment]
> Correct me if I'm wrong, but the source uses the `Boolean` function to convert the string values to a boolean, in my testing this produced `true` when calling it on `"false"`. Any yes/no questions will result it yes even if you pick no.

Why is JavaScript so weird

**Comment by Puyodead1** [comment]
#58

**Comment by face-hh** [comment]
Fixed
