### ISSUE TITLE
ADD EMAIL LOGIN

### ISSUE THREAD

**Issue by FFUV** [face-hh/lyntr#77]
PLEASE JUST ADD EMAIL OR APPLE OR GOOGLE ACC LOGIN MAN THIS IS OUTRAGEOUS

**Comment by GStudiosX2** [comment]
> PLEASE JUST ADD EMAIL OR APPLE OR GOOGLE ACC LOGIN MAN THIS IS OUTRAGEOUS

https://github.com/face-hh/lyntr/issues/6#issuecomment-2254667027
https://github.com/face-hh/lyntr/issues/24#issuecomment-2269776695
