### ISSUE TITLE
failed to delete account

### ISSUE THREAD

**Issue by cupboardmanufacturer** [face-hh/lyntr#79]
i tryed deleteing my account but it failed, probably becasue i accedently clicked on logout and it didnt then i deleted it.

**Comment by GStudiosX2** [comment]
> i tryed deleteing my account but it failed, probably becasue i accedently clicked on logout and it didnt then i deleted it.

https://github.com/face-hh/lyntr/issues/59#issuecomment-2272272835

**Comment by cupboardmanufacturer** [comment]
nvm i just made a new one for the thing i was trying to do
