### ISSUE TITLE
Gifs dont work

### ISSUE THREAD

**Issue by CodeName-Anti** [face-hh/lyntr#8]
Gifs get converted to an image.

[Example post](https://lyntr.com?id=5825578703919104)
[Original gif](https://media1.tenor.com/m/xwhNNv6-lDgAAAAC/h-apple-apple-h.gif)

**Comment by face-hh** [comment]
GIFs are not supported and not a priority.

**Comment by RealPacket** [comment]
> GIFs are not supported and not a priority.

The code is a 1 line change (or... at least I think)
