### ISSUE TITLE
Button feedback

### ISSUE THREAD

**Issue by buffsheep** [face-hh/lyntr#83]
Buttons like Home, Search, Notification and profile have feedback for hovering. But others dont, making some UI feel Unresponsive.
![image](https://github.com/user-attachments/assets/da3ce3c9-497b-4fbd-a3da-5b3374c10c31)
![image](https://github.com/user-attachments/assets/0a8b3641-097f-4a69-9bd6-1c1597785b86)

**Comment by face-hh** [comment]
Intended behavior. Not everything has to have the same effect.
