### ISSUE TITLE
Unexpected/awkward content scaling.

### ISSUE THREAD

**Issue by NathanX-S** [face-hh/lyntr#87]
The main 'feed' should fill the entire width of the page, until content is clicked on which should push the feed to the side if Lyntr intends to keep their layout this way.

Otherwise, even if no content is clicked, there's extremely awkward empty space issues.

**Comment by GStudiosX2** [comment]
> The main 'feed' should fill the entire width of the page, until content is clicked on which should push the feed to the side if Lyntr intends to keep their layout this way.
> 
> Otherwise, even if no content is clicked, there's extremely awkward empty space issues.

IMO it looks weird when it fills the entire width

**Comment by face-hh** [comment]
People like the current version more.
![image](https://github.com/user-attachments/assets/32dd5b14-7b2c-469e-b902-1543e459ad9a)

**Comment by NathanX-S** [comment]
@face-hh Can this be reopened? This doesn't mean the current layout can't be improved upon, and that vote hardly edged out over the other layout.
