### ISSUE TITLE
Rewrite in bussin

### ISSUE THREAD

**Issue by Sveagruva** [face-hh/lyntr#89]
Hello everybody, we should rewrite project in bussin (https://github.com/face-hh/bussin) because it's clearly a better language.

After conducting an exhaustive review it has been determined that rewriting the project in Bussin' will be beneficial for one primary reason:

1.  Clarity of Intention: By using Bussin', we can clearly communicate to the world that we have no idea what we're doing, but we're trying something new anyway.

In other words, the use of Bussin' as a programming language is not about improving performance, efficiency, or scalability; it's simply a declaration of our willingness to experiment and push boundaries. By embracing the uncertainty and unpredictability of Bussin', we can:

  - **Prove our audacity: Show the world that we're willing to take risks and challenge conventional wisdom.**
  - **Demonstrate our lack of expertise: Clearly convey that we have no experience with Bussin' or its ecosystem.**
  - **Set a new standard for chaos: Establish a benchmark for code complexity, debugging nightmares, and system crashes.**

To achieve this goal, we will:

1.  **Rush into implementation: Quickly rewrite the project in Bussin', without conducting thorough testing or analysis.**
2.  **Ignore best practices: Disregard established guidelines and conventions to create something truly unique and unpredictable.**
3.  **Pray for the best: Hope that our code somehow magically works, despite the odds.**

By rewriting the project in Bussin', we can boldly declare our intent to confuse, bewilder, and possibly even crash the system. It's a declaration of independence from sanity, and we're proud to be at the forefront of this revolution!

**Comment by FoxTale-Labs** [comment]
I do not see how this would really help with this project in any significant way, probably only impacting performance and making this harder to maintain.
With bussin not being a properly stable or, infact, to be taken serious language, rewriting this social media to bussin would only make more problems than good.
I doubt this will really be too desired for this project, but what you could try is on your own fork do this project for the funsies and use it as some coding practice I suppose!
Good luck!

**Comment by GamebP** [comment]
💀
