### ISSUE TITLE
[Feature Request] Using supabase backendless to directly call database for calls instead of your server

### ISSUE THREAD

**Issue by FoxTale-Labs** [face-hh/lyntr#90]
Related to issue -> #88 
Adding to that I also want to migrate this to use supabase so the performance will be significantly improved and your server won't die no more. This will allow your server to chill a little as post creation, liking, disliking, and replies, etc. would go directly to supabase instead of an in-between.
This requires supabase rules to be setup though to prevent abuse, but is a fair trade considering it'll significantly help with the sites performance.

**Comment by FoxTale-Labs** [comment]
I could implement this if you please while doing #88 after #20   has been implemented.

**Comment by FoxTale-Labs** [comment]
Adding: Things like the IQ test would likely still have to be passed through to the server for validation, and small things like image uploads (if you're not using supabase buckets, idk, didn't check yet). But we'd need to migrate to Supabase authentication, which won't be too hard honestly. Migrating to supabase authentication also gives the ability to get rid of discord login as then you won't need an SMTP server as supabase will send the verification emails out by themselves on their end for free.

**Comment by GStudiosX2** [comment]
> Related to issue -> #88 
> Adding to that I also want to migrate this to use supabase so the performance will be significantly improved and your server won't die no more. This will allow your server to chill a little as post creation, liking, disliking, and replies, etc. would go directly to supabase instead of an in-between.
> This requires supabase rules to be setup though to prevent abuse, but is a fair trade considering it'll significantly help with the sites performance.

They already migrated away from supabase I think so I don't see why they'd want to go back to it

**Comment by FoxTale-Labs** [comment]
> > Related to issue -> #88
> > Adding to that I also want to migrate this to use supabase so the performance will be significantly improved and your server won't die no more. This will allow your server to chill a little as post creation, liking, disliking, and replies, etc. would go directly to supabase instead of an in-between.
> > This requires supabase rules to be setup though to prevent abuse, but is a fair trade considering it'll significantly help with the sites performance.
> 
> They already migrated away from supabase I think so I don't see why they'd want to go back to it

oh damn i didnt know

**Comment by FoxTale-Labs** [comment]
well that sucks

**Comment by FoxTale-Labs** [comment]
package json still had references to supabase so i assumed he didnt migrate

**Comment by Linker-123** [comment]
It was a problem with indexing, not the fact that we self hosted postgres. Also supabase was asking 25 dollars for a 2 core machine which is very overpriced and it couldn't handle the traffic.

**Comment by FoxTale-Labs** [comment]
darn

**Comment by FoxTale-Labs** [comment]
ok then
